#!/usr/bin/env bash

echo "[Blog] Copying credentials to the server"
scp ./config/credentials/production.yml.enc ubuntu@shire.stanko.io:/home/ubuntu/container_data/blog/credentials/production.yml.enc
ssh ubuntu@shire.stanko.io "sudo chown 1000:1000 /home/ubuntu/container_data/blog/credentials/production.yml.enc"
