default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= Rails.application.credentials.dig(:database, :url) || 'postgres://postgres:postgres@127.0.0.1/blog' %>_<%= Rails.env %>

development:
  <<: *default

test:
  <<: *default


production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:database, :url) %>
