default: &default
  default_host: 'http://localhost:3030'
  allowed_hosts:
    - stanko.io
    - stanko.test
    - staging.stanko.io
    - cintra.local
    - 127.0.0.1
    - localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  default_host: 'https://stanko.io'
