test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/files") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage", Rails.env, "files") %>

scaleway:
  service: S3
  access_key_id: <%= Rails.app.creds.option(:scaleway_access_key_id) %>
  secret_access_key: <%= Rails.app.creds.option(:scaleway_secret_access_key) %>
  region: fr-par
  bucket: assets.stanko.io
  endpoint: https://s3.fr-par.scw.cloud
  public: true
